# Generated by Django 4.1 on 2022-08-28 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='collects',
            field=models.ManyToManyField(blank=True, to='app01.articles', verbose_name='收藏的文章'),
        ),
    ]
