# Generated by Django 4.1 on 2022-09-06 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_alter_userinfo_collects'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='pwd',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='文章密碼'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='category',
            field=models.IntegerField(blank=True, choices=[(0, '前端'), (1, '後端'), (2, '項目相關')], null=True, verbose_name='文章分類'),
        ),
    ]
