# Generated by Django 4.1 on 2022-09-06 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_articles_pwd_alter_articles_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='文章連結'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='status',
            field=models.IntegerField(choices=[(0, '未發佈'), (1, '已發佈')], verbose_name='文章保存狀態'),
        ),
    ]
