# Generated by Django 4.1 on 2022-09-23 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_articles_link_alter_articles_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='word',
            field=models.IntegerField(default=0, verbose_name='文章字數'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='category',
            field=models.IntegerField(blank=True, choices=[(1, '前端'), (2, '後端'), (3, '項目相關')], null=True, verbose_name='文章分類'),
        ),
    ]
