# Generated by Django 4.1 on 2022-11-29 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_articles_word_alter_articles_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='moods',
            name='addr',
            field=models.JSONField(null=True, verbose_name='用戶地址信息'),
        ),
        migrations.AddField(
            model_name='moods',
            name='ip',
            field=models.GenericIPAddressField(default='114.33.106.143', verbose_name='IP地址'),
        ),
        migrations.AlterField(
            model_name='moods',
            name='create_date',
            field=models.DateField(auto_now=True, verbose_name='發佈時間'),
        ),
    ]
