# Generated by Django 4.1 on 2022-12-01 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0009_moodcomment_addr_moodcomment_ip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moodcomment',
            name='addr',
        ),
        migrations.RemoveField(
            model_name='moodcomment',
            name='ip',
        ),
    ]
