# Generated by Django 4.1 on 2022-12-01 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0012_remove_moodcomment_addr_remove_moodcomment_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='moodcomment',
            name='addr',
            field=models.JSONField(null=True, verbose_name='用戶地址信息'),
        ),
        migrations.AddField(
            model_name='moodcomment',
            name='ip',
            field=models.GenericIPAddressField(default='114.33.106.143', verbose_name='IP地址'),
        ),
    ]
